sudo: false

language: go

go:
  #- 1.8
  - 1.9.x
  #- 1.10.x
  #- tip

go_import_path: github.com/prometheus/node_exporter

script:
  - make
  - make test
  - make tarball

deploy:
  provider: releases
  api_key:
    secure: scJ9oo3f73PKIsJcxBMw5b5NTD80pCOfYfNGrSrmwutEy0KEiolJx+i5XH4ruJy6W7aFdWyBzZkGt5ItyTKoPvyWwWZ0ubvdWnaXvR5hHC3hlRrE83WuHzoIdKuZBhsBn3z5gYdSj0tO9B21jAL6TeREB9ohH8ZKaKXxc4kKTtQQZ/heGxt+ynAOFWnJBZRuKiTsrAqujYbzSCR8875iLXZxzXgB/wQLf778dFwrVPvuMLlMdIfK/m2NT2cDAEMknAVdL1UNHd3HZAZjUy6EBW6mZpUjxBfP8Vk6MsU7wFdii6yNaSMWTxi7cXLYDuMBVeimdjkGU14I0FtQLVeL6yLNW4kLkTsG6GziCaCkN79oB2Zd5+u62EI7dTWL9Hb1J32uOa8dfTawp1JmzOmynPjEwoCNEMnT4c1xV7EPsoYhEIyQQJmArYzRFBMCosiclyV0svL3gN9Ale3UBK9ttb/P1M3M1/pLl+qol0kireF3UHJVSEhyUR7XwJxzpLmx6xg+HCsnJgwYqzDJ5TUABwi8ZrncyyReImrY05iSrQNAh3F90qOj4I8VkLYEgNPdGHrLusQWwL2sYsYN4M6PzD7/ttsdlJixf6fyn+m3bqSZwYc900yuBOqI9pMcRwb0NGmU8FxTg+rNHS+mZfDl6oFAdUEFgF+rpSLKvZQFA10=
  file_glob: true
  file: node_exporter*.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

notifications:
  webhooks: https://hook.bearychat.com/=bwA8s/travis/86c26c0c77edfb9fddf59e71b315625f

